name: Build Flutter Web
on: push

jobs:
  build_documentation:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter pub upgrade
        run: flutter pub upgrade

      - name: Flutter build web
        run: flutter build web --web-renderer canvaskit

      # Add this step to modify the base href after the build
      - name: Update base href for GitHub Pages
        run: |
          sed -i 's|<base href="/" />|<base href="https://msisaif.github.io/flutter-7-module-13-crud-app/" />|' build/web/index.html

      - name: Release the documentation
        uses: crazy-max/ghaction-github-pages@v3
        if: success()
        with:
          target_branch: build
          build_dir: build/web
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

